package com.gastrocontrol.gastrocontrol.entity;

import jakarta.persistence.*;

import java.time.Instant;

/**
 * JPA entity for products.
 *
 * Notes:
 * - `id` is database-generated (AUTO_INCREMENT in MySQL).
 * - We keep a protected no-args constructor for JPA.
 * - Setters are provided because the service layer mutates the entity.
 */
@Entity
@Table(name = "products")
public class ProductJpaEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 160)
    private String name;

    @Column(columnDefinition = "TEXT")
    private String description;

    @Column(nullable = false)
    private int priceCents;

    @Column(nullable = false)
    private boolean active = true;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    private CategoryJpaEntity category;

    @Column(name = "discontinued_at")
    private Instant discontinuedAt;

    @Column(name = "discontinued_reason", length = 255)
    private String discontinuedReason;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "discontinued_by_user_id")
    private UserJpaEntity discontinuedBy;

    protected ProductJpaEntity() {
        // for JPA
    }

    /**
     * Constructor for creating new products (id is generated by DB).
     */
    public ProductJpaEntity(String name, String description, int priceCents, boolean active, CategoryJpaEntity category) {
        this.name = name;
        this.description = description;
        this.priceCents = priceCents;
        this.active = active;
        this.category = category;
    }

    // Getters
    public Long getId() { return id; }
    public String getName() { return name; }
    public String getDescription() { return description; }
    public int getPriceCents() { return priceCents; }
    public boolean isActive() { return active; }
    public CategoryJpaEntity getCategory() { return category; }
    public Instant getDiscontinuedAt() { return discontinuedAt; }
    public String getDiscontinuedReason() { return discontinuedReason; }
    public UserJpaEntity getDiscontinuedBy() { return discontinuedBy; }

    // Setters (used by ManagerProductService)
    public void setName(String name) { this.name = name; }
    public void setDescription(String description) { this.description = description; }
    public void setPriceCents(int priceCents) { this.priceCents = priceCents; }
    public void setActive(boolean active) { this.active = active; }
    public void setCategory(CategoryJpaEntity category) { this.category = category; }
    public void setDiscontinuedAt(Instant discontinuedAt) { this.discontinuedAt = discontinuedAt; }
    public void setDiscontinuedReason(String discontinuedReason) { this.discontinuedReason = discontinuedReason; }
    public void setDiscontinuedBy(UserJpaEntity discontinuedBy) { this.discontinuedBy = discontinuedBy; }
}
