// src/main/java/com/gastrocontrol/gastrocontrol/infrastructure/persistence/entity/ProductJpaEntity.java
package com.gastrocontrol.gastrocontrol.infrastructure.persistence.entity;

import jakarta.persistence.*;
import java.time.Instant;

/**
 * JPA entity for products.
 *
 * <p>The {@code imageUrl} column stores a server-relative path to the product's
 * hero image (e.g. {@code /gastrocontrol/uploads/products/42.webp}).
 * It is {@code null} when no image has been uploaded.</p>
 *
 * Notes:
 * - {@code id} is database-generated (AUTO_INCREMENT in MySQL).
 * - A protected no-args constructor is required by JPA.
 * - Setters are provided because the service layer mutates the entity.
 */
@Entity
@Table(
        name = "products",
        uniqueConstraints = @UniqueConstraint(name = "uq_products_name", columnNames = "name")
)
public class ProductJpaEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 160)
    private String name;

    @Column(columnDefinition = "TEXT")
    private String description;

    /** Server-relative URL of the product image, or {@code null} if none uploaded. */
    @Column(name = "image_url", length = 500)
    private String imageUrl;

    @Column(nullable = false)
    private int priceCents;

    @Column(nullable = false)
    private boolean active = true;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    private CategoryJpaEntity category;

    @Column(name = "discontinued_at")
    private Instant discontinuedAt;

    @Column(name = "discontinued_reason", length = 255)
    private String discontinuedReason;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "discontinued_by_user_id")
    private UserJpaEntity discontinuedBy;

    protected ProductJpaEntity() {}

    /**
     * Constructor for creating new products (id is generated by DB).
     *
     * @param name        display name; must be unique across all products
     * @param description optional marketing description
     * @param priceCents  price in the smallest currency unit (euro cents)
     * @param active      whether the product appears on the public menu
     * @param category    the category this product belongs to, or {@code null}
     */
    public ProductJpaEntity(String name, String description, int priceCents, boolean active, CategoryJpaEntity category) {
        this.name        = name;
        this.description = description;
        this.priceCents  = priceCents;
        this.active      = active;
        this.category    = category;
    }

    // ── Getters ──────────────────────────────────────────────────────────────

    public Long getId()                  { return id; }
    public String getName()              { return name; }
    public String getDescription()       { return description; }
    public String getImageUrl()          { return imageUrl; }
    public int getPriceCents()           { return priceCents; }
    public boolean isActive()            { return active; }
    public CategoryJpaEntity getCategory()       { return category; }
    public Instant getDiscontinuedAt()   { return discontinuedAt; }
    public String getDiscontinuedReason(){ return discontinuedReason; }
    public UserJpaEntity getDiscontinuedBy()     { return discontinuedBy; }

    // ── Setters ──────────────────────────────────────────────────────────────

    public void setName(String name)                          { this.name = name; }
    public void setDescription(String description)            { this.description = description; }
    public void setImageUrl(String imageUrl)                  { this.imageUrl = imageUrl; }
    public void setPriceCents(int priceCents)                 { this.priceCents = priceCents; }
    public void setActive(boolean active)                     { this.active = active; }
    public void setCategory(CategoryJpaEntity category)       { this.category = category; }
    public void setDiscontinuedAt(Instant discontinuedAt)     { this.discontinuedAt = discontinuedAt; }
    public void setDiscontinuedReason(String reason)          { this.discontinuedReason = reason; }
    public void setDiscontinuedBy(UserJpaEntity user)         { this.discontinuedBy = user; }
}